DROP TABLE IF EXISTS `SIMULATION_RESULT`;
DROP TABLE IF EXISTS SIMULATION;

CREATE TABLE `SIMULATION` (
    `SIMULATION_ID` int(11) NOT NULL AUTO_INCREMENT,
    `NUMBER_DICE` int(11) NOT NULL,
    `DICE_SIDES` int(11) NOT NULL,
    `TOTAL_ROLLS` int(11) DEFAULT NULL,
    PRIMARY KEY (`SIMULATION_ID`)
);
CREATE TABLE `SIMULATION_RESULT` (
    `SIMULATION_RESULT_ID` int(11) NOT NULL AUTO_INCREMENT,
    `SUM_ROLLS` int(11) DEFAULT NULL,
    `FREQUENCY` int(11) DEFAULT NULL,
    `SIMULATION_ID` int(11) DEFAULT NULL,
    CONSTRAINT `SIMULATION_ID_FK`
        FOREIGN KEY (`SIMULATION_ID`)
        REFERENCES `SIMULATION` (`SIMULATION_ID`)
);